# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: base

# ---------------------------
# Logging & Tracking
# ---------------------------

logger:
  dir: logger

# ---------------------------------------
# Example of User Section
# ---------------------------------------

train:
    lr: 0.001